name: Microservices CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        service: [frontend, cartservice]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker Context
        id: docker_context
        run: |
          if [ "${{ matrix.service }}" = "cartservice" ]; then
            echo "path=./src/cartservice/src" >> $GITHUB_OUTPUT
          else
            echo "path=./src/frontend" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ steps.docker_context.outputs.path }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.service }}:latest

      - name: Update Kustomize images
        run: |
          NEW_IMAGE="ghcr.io/${{ github.repository }}/${{ matrix.service }}"
          
          echo "Updating Staging..."
          cd k8s/overlays/staging
          kustomize edit set image ${{ matrix.service }}=${NEW_IMAGE}:latest
          
          echo "Updating Production..."
          cd ../production
          kustomize edit set image ${{ matrix.service }}=${NEW_IMAGE}:latest
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Додаємо зміни, але якщо виникне конфлікт під час pull, 
          # ми кажемо git віддати перевагу нашим локальним змінам для цього файлу
          git add .
          git commit -m "Update ${{ matrix.service }} image to latest" || exit 0
          
          # Спроба злиття з сервером з автоматичним вирішенням конфліктів
          # (повторюємо до 3 разів у разі невдачі)
          for i in {1..3}; do
            git pull --rebase origin main && git push origin main && break || \
            (git rebase --abort; git pull --rebase origin main; git commit -am "Update ${{ matrix.service }} image"; sleep 5)
          done
