apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: staging
namePrefix: stg-
images:
- name: cartservice
  newName: ghcr.io/viaolympia/ncodeks-int/cartservice
  newTag: latest
- name: frontend
  newName: ghcr.io/viaolympia/ncodeks-int/frontend
  newTag: latest
